### ISSUE TITLE
Support text annotations

### ISSUE THREAD

**Issue by MattesGroeger** [MattesGroeger/vim-bookmarks#29]
Optionally add annotations to bookmarks with shortcut `mi`. This is useful for preparing a code review.
#### Tasks:
- [x] Update `bm.vim` to support annotations
- [x] Add `:Annotate` command
- [x] When on line without bookmark open insert dialog and add bookmark
- [x] When on line with bookmark open insert dialog
- [x] When on line with bookmark and annotation open edit dialog
- [x] Add shortcut `mi` for adding annotations (`i` for insert annotation)
- [x] Add annotations to persistence layer
- [x] Show annotation in quicklist instead of line content (if set)
- [x] Show annotation when jumping to bookmark
- [x] Different color for annotations (configurable)
- [x] Document feature (`Readme.md` & `bookmarks.txt`)
